### ISSUE TITLE
How to download the module

### ISSUE THREAD

**Issue by Karimpop0099** [Magisk-Modules-Repo/OneController#20]

**Comment by yum13241** [comment]
I have the same question.

**Comment by sastreae** [comment]
Si estas desde celular. Tenes que poner el navegador en modo escritorio. Luego te da la opción para descargar como zip. Aun así.   Magisk no logra descomprimirlo

**Comment by Synskiav** [comment]
So, download the zip file but take the files from the folder, which is in the zip archive out and put all files into a new zip archive NOT RAR archive!

**Comment by nathanfranke** [comment]
You can fix the zip within the Android AOSP Files app:
1) Code→Download ZIP on GitHub
2) Open `OneController-master.zip` on Files, select the root folder within, Menu→Extract to..., Extract
3) Navigate to the extracted folder in Downloads
4) Select all files, Menu→Compress
5) Open Magisk and install the new archive.zip

That being said, a release with a fixed zip attached would be nice.
