### ISSUE TITLE
Xbox one controller doesnt work on Lenovo tab3 10 Business Tablet

### ISSUE THREAD

**Issue by Imikeeee** [Magisk-Modules-Repo/OneController#3]
The device is rooted with magisk boot patch.

I have a OTG cable , when i plug in the controller , it vibrate but the xbox button wont light up and the buttons are not working.
After i donwloaded the module in magisk, rebooted and nothing .
Im donwloaded several otg tester , gamepad tester, the otg tester can see the connection but nothing else.

How can i solve this problem?

( First generation(fat) xbox one controller)

**Comment by Imikeeee** [comment]
OTG GURU app from play store log


ID: 0
Path: /dev/bus/usb/001/006
VID: 0x045E (Microsoft Corp.)
PID: 0x02DD (Xbox One Controller (Firmware 2015))
Class: 255 (USB_CLASS_VENDOR_SPEC)
Subclass: 71
Protocol: 208
5 Interfaces:
  ID: 0
  Class: 255 (USB_CLASS_VENDOR_SPEC)
  Subclass: 71
  Protocol: 208
  2 Endpoints:
    ID: 0
    Descriptor: [0x07 0x05 0x01 0x03 0x40 0x00 0x04]
    Address: 0x01
      Endpoint Number: 1
      Direction: 0 (host to device)
    Attributes: 0b00000011
      Type: 0b11 (Interrupt)
    Max. Packet Size: 64 Bytes
    Interval: 4
    ID: 1
    Descriptor: [0x07 0x05 0x81 0x03 0x40 0x00 0x04]
    Address: 0x81
      Endpoint Number: 1
      Direction: 1 (device to host)
    Attributes: 0b00000011
      Type: 0b11 (Interrupt)
    Max. Packet Size: 64 Bytes
    Interval: 4
  ID: 1
  Class: 255 (USB_CLASS_VENDOR_SPEC)
  Subclass: 71
  Protocol: 208
  0 Endpoints:
  ID: 2
  Class: 255 (USB_CLASS_VENDOR_SPEC)
  Subclass: 71
  Protocol: 208
  2 Endpoints:
    ID: 0
    Descriptor: [0x07 0x05 0x02 0x01 0xE4 0x00 0x01]
    Address: 0x02
      Endpoint Number: 2
      Direction: 0 (host to device)
    Attributes: 0b00000001
      Type: 0b01 (Isochronous)
    Max. Packet Size: 228 Bytes
    Interval: 1
    ID: 1
    Descriptor: [0x07 0x05 0x82 0x01 0xE4 0x00 0x01]
    Address: 0x82
      Endpoint Number: 2
      Direction: 1 (device to host)
    Attributes: 0b00000001
      Type: 0b01 (Isochronous)
    Max. Packet Size: 228 Bytes
    Interval: 1
  ID: 3
  Class: 255 (USB_CLASS_VENDOR_SPEC)
  Subclass: 71
  Protocol: 208
  0 Endpoints:
  ID: 4
  Class: 255 (USB_CLASS_VENDOR_SPEC)
  Subclass: 71
  Protocol: 208
  2 Endpoints:
    ID: 0
    Descriptor: [0x07 0x05 0x03 0x02 0x40 0x00 0x00]
    Address: 0x03
      Endpoint Number: 3
      Direction: 0 (host to device)
    Attributes: 0b00000010
      Type: 0b10 (Bulk)
    Max. Packet Size: 64 Bytes
    Interval: 0
    ID: 1
    Descriptor: [0x07 0x05 0x83 0x02 0x40 0x00 0x00]
    Address: 0x83
      Endpoint Number: 3
      Direction: 1 (device to host)
    Attributes: 0b00000010
      Type: 0b10 (Bulk)
    Max. Packet Size: 64 Bytes
    Interval: 0

**Comment by Electric1447** [comment]
https://play.google.com/store/apps/details?id=ru.elron.gamepadtester

Download this app and check if it detects the controller

**Comment by Imikeeee** [comment]
Doesnt see

**Comment by Electric1447** [comment]
1Controller is a keymap fixer for controllers thus it does not contain/relay on any drivers.
If your device cannot detect a certain controller I cannot do anything about it.

**Comment by Electric1447** [comment]
Closed for now, update here if anything changes
