### ISSUE TITLE
add xbox original controller

### ISSUE THREAD

**Issue by abasgames** [Magisk-Modules-Repo/OneController#4]

**Comment by Electric1447** [comment]
What is the usb vendor and product id of the og xbox controller.
I also know there are 2 official controllers: The "Duke" and Controller S

**Comment by Electric1447** [comment]
I don't have an original xbox controller nor do I know someone who does.
However if you have one I can explain to you how to create the keylayout file.

**Comment by Kronyx** [comment]
Hi, I have a redmi note 9S, and I tried to use the Xbox 360 controller by OTG, but it didn't work.
If there's anything I can do to make it work, just say so.

**Comment by acidburn743** [comment]
### _**> XBOX/360/One Vendor&Product ID-List :**_


- 0x045e, 0x0202, Microsoft X-Box pad v1 (US), XTYPE_XBOX
- 0x045e, 0x0285, Microsoft X-Box pad (Japan), XTYPE_XBOX
- 0x045e, 0x0287, Microsoft Xbox Controller S, XTYPE_XBOX
- 0x045e, 0x0289, Microsoft X-Box pad v2 (US), XTYPE_XBOX
- 0x045e, 0x028e, Microsoft X-Box 360 pad, XTYPE_XBOX360
- 0x045e, 0x02d1, Microsoft X-Box One pad, XTYPE_XBOXONE
- 0x045e, 0x02dd, Microsoft X-Box One pad (Firmware 2015), XTYPE_XBOXONE
- 0x045e, 0x02e3, Microsoft X-Box One Elite pad, XTYPE_XBOXONEg
- 0x045e, 0x02ea, Microsoft X-Box One S pad, XTYPE_XBOXONE
- 0x045e, 0x0291, Xbox 360 Wireless Receiver (XBOX), XTYPE_XBOX360W
- 0x045e, 0x0719, Xbox 360 Wireless Receiver, XTYPE_XBOX360W
- 0x044f, 0x0f07, Thrustmaster Inc. Controller, XTYPE_XBOX
- 0x044f, 0xb326, Thrustmaster Gamepad GP XID, XTYPE_XBOX360
- 0x046d, 0xc21d, Logitech Gamepad F310, XTYPE_XBOX360
- 0x046d, 0xc21e, Logitech Gamepad F510, XTYPE_XBOX360
- 0x046d, 0xc21f, Logitech Gamepad F710, XTYPE_XBOX360
- 0x046d, 0xc242, Logitech Chillstream Controller, XTYPE_XBOX360
- 0x046d, 0xca84, Logitech Xbox Cordless Controller, XTYPE_XBOX
- 0x046d, 0xca88, Logitech Compact Controller for Xbox, XTYPE_XBOX
- 0x05fd, 0x1007, Mad Catz Controller (unverified), XTYPE_XBOX
- 0x05fd, 0x107a, InterAct 'PowerPad Pro' X-Box pad (Germany), XTYPE_XBOX
- 0x0738, 0x4516, Mad Catz Control Pad, XTYPE_XBOX
- 0x0738, 0x4522, Mad Catz LumiCON, XTYPE_XBOX
- 0x0738, 0x4526, Mad Catz Control Pad Pro, XTYPE_XBOX
- 0x0738, 0x4536, Mad Catz MicroCON, XTYPE_XBOX
- 0x0738, 0x4540, Mad Catz Beat Pad, XTYPE_XBOX
- 0x0738, 0x4556, Mad Catz Lynx Wireless Controller, XTYPE_XBOX
- 0x0738, 0x4716, Mad Catz Wired Xbox 360 Controller, XTYPE_XBOX360
- 0x0738, 0x4718, Mad Catz Street Fighter IV FightStick SE, XTYPE_XBOX360
- 0x0738, 0x4726, Mad Catz Xbox 360 Controller, XTYPE_XBOX360
- 0x0738, 0x4728, Mad Catz Street Fighter IV FightPad, XTYPE_XBOX360
- 0x0738, 0x4738, Mad Catz Wired Xbox 360 Controller (SFIV), XTYPE_XBOX360
- 0x0738, 0x4740, Mad Catz Beat Pad, XTYPE_XBOX360
- 0x0738, 0x4a01, Mad Catz FightStick TE 2, XTYPE_XBOXONE
- 0x0738, 0x6040, Mad Catz Beat Pad Pro, XTYPE_XBOX
- 0x0738, 0xb726, Mad Catz Xbox controller - MW2, XTYPE_XBOX360
- 0x0738, 0xbeef, Mad Catz JOYTECH NEO SE Advanced GamePad, XTYPE_XBOX360
- 0x0738, 0xcb02, Saitek Cyborg Rumble Pad - PC/Xbox 360, XTYPE_XBOX360
- 0x0738, 0xcb03, Saitek P3200 Rumble Pad - PC/Xbox 360, XTYPE_XBOX360
- 0x0738, 0xf738, Super SFIV FightStick TE S, XTYPE_XBOX360
- 0x0c12, 0x8802, Zeroplus Xbox Controller, XTYPE_XBOX
- 0x0c12, 0x8809, RedOctane Xbox Dance Pad, XTYPE_XBOX
- 0x0c12, 0x880a, Pelican Eclipse PL-2023, XTYPE_XBOX
- 0x0c12, 0x8810, Zeroplus Xbox Controller, XTYPE_XBOX
- 0x0c12, 0x9902, HAMA VibraX - *FAULTY HARDWARE*, XTYPE_XBOX
- 0x0d2f, 0x0002, Andamiro Pump It Up pad, XTYPE_XBOX
- 0x0e4c, 0x1097, Radica Gamester Controller, XTYPE_XBOX
- 0x0e4c, 0x2390, Radica Games Jtech Controller, XTYPE_XBOX
- 0x0e6f, 0x0003, Logic3 Freebird wireless Controller, XTYPE_XBOX
- 0x0e6f, 0x0005, Eclipse wireless Controller, XTYPE_XBOX
- 0x0e6f, 0x0006, Edge wireless Controller, XTYPE_XBOX
- 0x0e6f, 0x0105, HSM3 Xbox360 dancepad, XTYPE_XBOX360
- 0x0e6f, 0x0113, Afterglow AX.1 Gamepad for Xbox 360, XTYPE_XBOX360
- 0x0e6f, 0x0139, Afterglow Prismatic Wired Controller, XTYPE_XBOXONE
- 0x0e6f, 0x0201, Pelican PL-3601 'TSZ' Wired Xbox 360 Controller, XTYPE_XBOX360
- 0x0e6f, 0x0213, Afterglow Gamepad for Xbox 360, XTYPE_XBOX360
- 0x0e6f, 0x021f, Rock Candy Gamepad for Xbox 360, XTYPE_XBOX360
- 0x0e6f, 0x0146, Rock Candy Wired Controller for Xbox One, XTYPE_XBOXONE
- 0x0e6f, 0x0301, Logic3 Controller, XTYPE_XBOX360
- 0x0e6f, 0x0401, Logic3 Controller, XTYPE_XBOX360
- 0x0e8f, 0x0201, SmartJoy Frag Xpad/PS2 adaptor, XTYPE_XBOX
- 0x0e8f, 0x3008, Generic xbox control (dealextreme), XTYPE_XBOX
- 0x0f0d, 0x000a, Hori Co. DOA4 FightStick, XTYPE_XBOX360
- 0x0f0d, 0x000d, Hori Fighting Stick EX2, XTYPE_XBOX360
- 0x0f0d, 0x0016, Hori Real Arcade Pro.EX, XTYPE_XBOX360
- 0x0f0d, 0x0067, HORIPAD ONE, XTYPE_XBOXONE
- 0x0f30, 0x0202, Joytech Advanced Controller, XTYPE_XBOX
- 0x0f30, 0x8888, BigBen XBMiniPad Controller, XTYPE_XBOX
- 0x102c, 0xff0c, Joytech Wireless Advanced Controller, XTYPE_XBOX
- 0x12ab, 0x0004, Honey Bee Xbox360 dancepad, XTYPE_XBOX360
- 0x12ab, 0x0301, PDP AFTERGLOW AX.1, XTYPE_XBOX360
- 0x12ab, 0x8809, Xbox DDR dancepad, XTYPE_XBOX
- 0x1430, 0x4748, RedOctane Guitar Hero X-plorer, XTYPE_XBOX360
- 0x1430, 0x8888, TX6500+ Dance Pad (first generation), XTYPE_XBOX
- 0x146b, 0x0601, BigBen Interactive XBOX 360 Controller, XTYPE_XBOX360
- 0x1532, 0x0037, Razer Sabertooth, XTYPE_XBOX360
- 0x15e4, 0x3f00, Power A Mini Pro Elite, XTYPE_XBOX360
- 0x15e4, 0x3f0a, Xbox Airflo wired controller, XTYPE_XBOX360
- 0x15e4, 0x3f10, Batarang Xbox 360 controller, XTYPE_XBOX360
- 0x162e, 0xbeef, Joytech Neo-Se Take2, XTYPE_XBOX360
- 0x1689, 0xfd00, Razer Onza Tournament Edition, XTYPE_XBOX360
- 0x1689, 0xfd01, Razer Onza Classic Edition, XTYPE_XBOX360
- 0x24c6, 0x542a, Xbox ONE spectra, XTYPE_XBOXONE
- 0x24c6, 0x5d04, Razer Sabertooth, XTYPE_XBOX360
- 0x1bad, 0x0002, Harmonix Rock Band Guitar, XTYPE_XBOX360
- 0x1bad, 0x0003, Harmonix Rock Band Drumkit, XTYPE_XBOX360
- 0x1bad, 0xf016, Mad Catz Xbox 360 Controller, XTYPE_XBOX360
- 0x1bad, 0xf023, MLG Pro Circuit Controller (Xbox), XTYPE_XBOX360
- 0x1bad, 0xf028, Street Fighter IV FightPad, XTYPE_XBOX360
- 0x1bad, 0xf038, Street Fighter IV FightStick TE, XTYPE_XBOX360
- 0x1bad, 0xf900, Harmonix Xbox 360 Controller, XTYPE_XBOX360
- 0x1bad, 0xf901, Gamestop Xbox 360 Controller, XTYPE_XBOX360
- 0x1bad, 0xf903, Tron Xbox 360 controller, XTYPE_XBOX360
- 0x24c6, 0x5000, Razer Atrox Arcade Stick, XTYPE_XBOX360
- 0x24c6, 0x5300, PowerA MINI PROEX Controller, XTYPE_XBOX360
- 0x24c6, 0x5303, Xbox Airflo wired controller, XTYPE_XBOX360
- 0x24c6, 0x541a, PowerA Xbox One Mini Wired Controller, XTYPE_XBOXONE
- 0x24c6, 0x543a, PowerA Xbox One wired controller, XTYPE_XBOXONE
- 0x24c6, 0x5500, Hori XBOX 360 EX 2 with Turbo, XTYPE_XBOX360
- 0x24c6, 0x5501, Hori Real Arcade Pro VX-SA, XTYPE_XBOX360
- 0x24c6, 0x5506, Hori SOULCALIBUR V Stick, XTYPE_XBOX360
- 0x24c6, 0x5b02, Thrustmaster, Inc. GPX Controller, XTYPE_XBOX360
- 0x24c6, 0x5b03, Thrustmaster Ferrari 458 Racing Wheel, XTYPE_XBOX360
- 0xffff, 0xffff, Chinese-made Xbox Controller, XTYPE_XBOX9
- 0x0000, 0x0000, Generic X-Box pad, XTYPE_UNKNOWN

Have fun with it, greets 4c1d3uRn

**Comment by Electric1447** [comment]
Thanks!
I actually bought an original duke controller but I have no way of connecting it to the phone

**Comment by abasgames** [comment]
> Thanks!
> I actually bought an original duke controller but I have no way of connecting it to the phone

xbox original controller usb adapter + usb otg
