### ISSUE TITLE
I want to port some controllers I own to this project - what tool is used to find the scan codes for the controller?

### ISSUE THREAD

**Issue by intra0** [Magisk-Modules-Repo/OneController#40]
what tool is used to find the scan codes for the controller?

like how do you find 'key 0x132    BUTTON_X' for example??

**Comment by intra0** [comment]
Ok so I found the app https://play.google.com/store/apps/details?id=ru.elron.gamepadtester to test if I can get the controller to connect to android, but what if I'm having my device to even sync? (wii u pro controller)

**Comment by Electric1447** [comment]
If you cannot connect your controller via usb/Bluetooth, you may need an adapter.
Check if brook or mayflash have adapters for your controller.

**Comment by intra0** [comment]
Thats what I was afraid of hearing but it makes sense. I'll close this issue because my question has been answered.

also for future people reading this, .kl files are exclusive to my knowledge there's no way to find out what the scancodes are on another os (such as linux or windows), so the android gamepad test app is a must
