### ISSUE TITLE
DS4 v2 doesn't work

### ISSUE THREAD

**Issue by YungWalkie** [Magisk-Modules-Repo/OneController#9]
DS4 v2 doesn't work

**Comment by Electric1447** [comment]
I have 3 DS4 V2 controllers and they all work.

**Comment by YungWalkie** [comment]
> DS4 v2 doesn't work

After installing magisk, i saw that i can connect to my DS4 wireless controller, but it doesn't work, even after install this module and reboot system

**Comment by Electric1447** [comment]
I will need more information:
- Android version
- Phone model
- Connection method (BT/OTG)
- etc

**Comment by YungWalkie** [comment]
> I will need more information:
> 
> * Android version
> * Phone model
> * Connection method (BT/OTG)
> * etc

Android 10, Pixel Experience official rom
Redmi 5 Plus
Bluetooth

You can say that because of this "custom" rom, but previously it worked fine, only after installing PE plus Magisk it doesn't work. Light on my controller work a bit, but i cannot press buttons even after installing module. Magisk and module if full updated, in the log i saw that it boot correctly

**Comment by YungWalkie** [comment]
My controller work fine on pc btw

**Comment by Electric1447** [comment]
I need you to also try using OTG
